### ISSUE TITLE
EPG Import improvement when loading epg.dat from the net

### ISSUE THREAD

**Issue by pr2git** [OpenPLi/enigma2-plugin-extensions-xmltvimport#27]
Hi,
 
In EPG Import  there is an experimental section
 
**** Rytec EPG.DAT (Experimental - Use at own risk) ****
 
I test it and it is working fine for me.
 
But there is a border effect with the option:  delete current EPG before importing.
 
If you select multiple epg.dat files (exemple BeNeLux & France) in the sources and if you have delete current EPG before importing set to Yes,  then it is only the lastest epg.dat file processed that remains in EPG memory.
 
So I think that the EPG memory delete should be performed (if set) before the loop that process many epg.dat files.
 
This will allow us to have the delete current EPG set to Yes and select multiple epg.dat files without any problem.
 
Regards,
 
Pr2

Check discussion here:

https://forums.openpli.org/topic/43612-epg-import-improvement-when-loading-epgdat-from-the-net/

**Comment by Dima73** [comment]
delete current EPG --> epg.dat and RAM
new epg.dat 1 ->epg.dat 1 load
delete current EPG --> epg.dat and RAM
new epg.dat 2 ->epg.dat 2 load
I do not understand the logic ???

**Comment by milosoftware** [comment]
I think you cannot really load multiple epg.dat files safely.

The epg.dat stores internal links and reference counts. The second epg.dat file, if it contains the same event descriptors, will overwrite some of these. Things will appear to work fine, but when the events are being removed, the reference counters will not match and descriptors will be deleted while still in use by other events. This will result in missing event texts and it will cause the EPG to be marked "corrupt" so it will not be written to a file. It may even crash the system at some point.

**Comment by WanWizard** [comment]
I read it differently, but the TS has to clarify.

There is an option to delete all loaded EPG before starting the import. From the original question it appears to me this delete runs before EACH epg.dat import, and not only before the first one. So if you first import UK, and then France, all UK info is gone.

**Comment by milosoftware** [comment]
I'll phrase it simply: Importing an epg.dat is a BAD IDEA. It only works if you load a single file, and then only after you've deleted all EPG first. Anything else (like loading two epg.dat files, or not deleting the existing EPG first) is a recipe for disaster.
