### ISSUE TITLE
exclusions

### ISSUE THREAD

**Issue by eXim82** [OpenPLi/enigma2-plugin-extensions-xmltvimport#28]
hi. it would be great to do exclusions, such as single channels or bouqets. example: rytek italy does provide some epg data for germany channels, but the times are wrong. i do for german channels epgrefresh, because of inaccurate times. so after an epg import i have for the same program two times (exmpl. 20:14 greys anatomie, 20:15 greys anatomie). so it would be great, to do exclusions for german channels. thank you.

**Comment by milosoftware** [comment]
I guess you're not expecting a checkbox that says "exclude the German channels"?

You can change the channels affected by creating your own "channels" file. That allows you to skip any channel you'd like.

**Comment by eXim82** [comment]
a checkbox like "exclude german channels", or better " exclude some german channels" would be great. But it were sufficent to have an option to exclude individual channels or bouquets.

a channel file? you mean settings, right? that is not an option for me, because i look german and italian channels. But, because the rytec epg has faulty times for the german epg, and do also update some german channels, it would be great to do exclusions. for the german channels i use epgrefresh and for the italians i want xmltimporter, because they do not provide epg data on the channels itself (tivusat).

**Comment by WanWizard** [comment]
No, he means a channels file. A custom file that maps an XML channel definition to a service reference, instead of the standard Rytec files that you enable/disable in the plugin.

If you want to take this route, I suggest you join the forum and discuss this in the Rytec forums. The issue tracker is no place for discussions.
